language: node_js
dist: trusty
node_js:
  - v10
cache:
  yarn: true
  directories:
  - ~/.npm

before_install:
  - START_TIME=$(date +%s)
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24+32"
  - |
    export RECORDED_FILE="$(pwd)/recorded.mp4"
    coproc ffmpeg -f x11grab -video_size 1920x1080 -i :0 -codec:v libx264 -r 60 "$RECORDED_FILE" &
    export COPR=$COPROC
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

before_script:
  - |
    if [[ "${METAMASK_NETWORK:0:1}" = "l"  ]] || [[ -z "${METAMASK_NETWORK+x}" ]]; then
      ARGS="$ARGS --params.setup.ganache=true"
    fi

script: npm test -- --env=production --params.tags=@status $ARGS

after_script:
  - |
    echo 'q' >&"${COPR[1]}"
    # Upload video somewhere
  - |
    END_TIME=$(date +%s)
    ELAPSED=$(($END_TIME - $START_TIME))
    JOB_EXPECTED_TIME=$((60 * 10))
    # We can trigger scripts maximum 10 times per hour
    if [[ $ELAPSED < $JOB_EXPECTED_TIME ]]; then
      TIMELEFT=$((JOB_EXPECTED_TIME - $ELAPSED))
      echo "Waiting $TIMELEFT seconds to trigger the next job..."
      sleep $TIMELEFT
    fi;
  - bash trigger.sh

notifications:
  email:
    - josep@polymath.network